### ISSUE TITLE
Could you share manual ? 

### ISSUE THREAD

**Issue by durul** [jfix/dash-button#2]
Hello,

Coudl you share manual ? Because some details are not clear. Which format or how could we update filename and details ?  

I am receiving error Client requires an Account SID and Auth Token set explicitly or via the TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN environment variables

**Comment by jfix** [comment]
Twilio account details are only required if you want to send SMS. If you don't want to send SMS, you should remove or comment our the respective code sections. Regarding the Twilio credentials, you have to set them up with Twilio first and then put them in your `.env` file (see `env.sample`).

**Comment by durul** [comment]
Thank you so much. Could you give me details for parameters below. 

MAC_SMS=yo:ur:ma:ca:dd:rs        
MAC_COFFEE=yo:ur:ma:ca:dd:rs

**Comment by jfix** [comment]
These are the MAC addresses for the Amazon Dash buttons you (should) have. To figure out which are the addresses of your buttons, see here: https://github.com/hortinstein/node-dash-button

**Comment by durul** [comment]
Ok I do it. Should I configure IFTTT and database-related information. I want to use just sms.

**Comment by jfix** [comment]
No you don't need the ifttt and the mongo stuff to send SMS.

On May 8, 2017 5:27 PM, "durul" <notifications@github.com> wrote:

Ok I do it. Should I configure IFTTT and database-related information. I
want to use just sms.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jfix/dash-button/issues/2#issuecomment-299900065>, or mute
the thread

**Comment by durul** [comment]
Almost done ...  Could you give me advice TWILIO_FROM_NUMBER format. 

We'll be sending this message: Hiya, love you
Problem sending SMS {"status":400,"message":"The From phone number +14435186448 is not a valid, SMS-capable inbound phone number or short code for your account.","code":21606,"moreInfo":"https://www.twilio.com/docs/errors/21606"}

**Comment by jfix** [comment]
Have a look at the link that's been provided by the response ... Your number format is likely correct, but it's not valid for Twilio, again see the documentation for an explanation

**Comment by durul** [comment]
thanks.
